### PR TITLE
Updated dependencies and runtime to Node 16

### PR DESCRIPTION
**Pull request by danielfeather**

### CODE REVIEW

**Comment by themichaelhall** [comment]
Hi Daniel,

Thank you for your pull request! 

It seems that the tests are failing. If you have any idea why, please feel free to commit a fix, otherwise I will look into it during the week.

Best regards

/Michael

**Comment by danielfeather** [comment]
Thanks for getting back @themichaelhall. I'll have a look at some point this week, I think it will be because of the major version change of Node.

**Comment by danielfeather** [comment]
Seems to have been because I didn't update the test workflow to Node 16.

**Comment by themichaelhall** [comment]
Great, thank you!

Since the auto-generated files are quite large, I will re-generate them locally myself, rather than review the changes. After that I will probably release v2 before the week is over.

**Pull request merged**
